# Generated by Django 4.2.3 on 2023-08-05 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamBlue', models.CharField(max_length=250)),
                ('teamRed', models.CharField(max_length=250)),
                ('scoreB', models.IntegerField(default=0)),
                ('scoreR', models.IntegerField(default=0)),
            ],
        ),
    ]
